language: java
sudo: false
jdk:
  - openjdk11
services:
  - postgresql
script:
  - psql -a -U postgres -c 'create database letter;'
  - psql -a -U postgres -d letter -f src/main/resources/database.sql
  - gradle test -Dfileupload.path=$HOME/upload
