language: java
sudo: false
jdk:
  - openjdk8
services:
  - postgresql
script:
  - psql -a -U postgres -c 'create database messenger;'
  - psql -a -U postgres -d messenger -f core/src/main/resources/database.sql
  - gradle build -i -Dfileupload.path=$HOME/upload