language: java
sudo: true
jdk:
  - openjdk8
services:
  - postgresql
script:
  - sudo -u postgres -i
  - sudo psql -a -U postgres -c 'create database messenger;'
  - sudo psql -a -U postgres -d messenger -f core/src/main/resources/database.sql
  - sudo mkdir /upload
  - sudo gradle build -i -Dfileupload.path=/upload