language: java
sudo: true
jdk:
  - openjdk8
services:
  - postgresql
script:
  - psql -a -U postgres -c 'create database messenger;'
  - psql -a -U postgres -d messenger -f core/src/main/resources/database.sql
#  - mkdir $HOME/upload
  - gradle build -i -Dfileupload.path=$HOME/upload