name: core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: letter
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: run db script
        run: psql -a -U postgres -d letter -f src/main/resources/database.sql

      - name: run tests
        run: gradle test -Dfileupload.path=$HOME/upload
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_DATABASE: postgres
          PG_PASSWORD: postgres
          PG_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
